package generator;

import java.util.ArrayList;

/**
 * This object class will handle the generation of a random haiku poem from an
 * analyzed source file.
 * 
 * @author Kyler McMullin
 *
 */
public class Generator {

	/**
	 * References a set of all known words in the source text
	 */
	private WordSet allWords;

	/**
	 * Used to build each line of the poem word by word
	 */
	private StringBuilder sBuilder;

	/**
	 * Contains all of the lines generated by the generator.
	 */
	private ArrayList<String> lines;

	/**
	 * Contains the finalized poem that the generator has generated.
	 */
	private String poem;

	/**
	 * Indicates whether or not the poem will be generated from the last word on the
	 * previous line. (I.E. if the last word of line 1 was "dog," the next line
	 * would start with a word that is known to follow "dog" in the source text)
	 */
	private boolean continuous;

	/**
	 * Constructs the Generator object with the necessary variables.
	 * 
	 * @param allWords:   the set of all words contained in the text
	 * @param continuous: whether or not the program should generate from the last
	 *                    word of the previous line
	 */
	public Generator(WordSet allWords, boolean continuous) {
		this.allWords = allWords;
		this.continuous = continuous;
	}

	/**
	 * Enacts the process of generating a poem.
	 */
	public void generate() {
		sBuilder = new StringBuilder();

		sBuilder.append(genLine(7));
		sBuilder.append(genLine(5));
		sBuilder.append(genLine(7));

		poem = sBuilder.toString();
	}

	/**
	 * Generates and returns a line of the poem, based on an integer variable which
	 * dictates how many syllables the line should contain.
	 * 
	 * @param syllables: the number of syllables the line should contain
	 * @return line
	 */
	private String genLine(int syllables) {
		//TODO:  Implement code to generate a line of a given syllable count
		return null;
	}

	/**
	 * Returns the poem last generated by the generator object.
	 * 
	 * @return poem
	 */
	public String getPoem() {
		return poem;
	}

}
